- app/scripts/components/facets/templates/current.html
- app/scripts/components/facets/templates/facet.html
> fix(components): 2527 don't humanify fields

- app/scripts/404/templates/404.html
- app/scripts/app.ts
> fix(app): 2477 otherwise 404, w/link back to files

- app/styles/app.less
> feat(app): 2573 visited link darker

- app/scripts/files/files.controllers.ts
- app/scripts/files/files.directives.ts
- app/scripts/files/templates/file.html
> feat(file): 2230 proj id in props table

- app/scripts/components/facets/facets.controllers.ts
- app/scripts/components/facets/templates/facet.html
- app/scripts/components/facets/templates/facets-date.html
- app/scripts/components/facets/templates/facets-free-text.html
- app/scripts/components/facets/templates/facets-prefix.html
- app/scripts/components/facets/templates/range-facet.html
> feat(facets): 2578 reset on all facet types

- app/scripts/annotations/module.ts
- app/scripts/annotations/templates/annotation.html
> feat(annotation): 747 case submitter_id in table

- app/scripts/app.ts
- app/scripts/cart/cart.controllers.ts
- app/scripts/cart/cart.services.ts
- app/scripts/components/facets/facets.models.ts
- app/scripts/components/ui/string/string.filters.ts
- app/scripts/files/files.controllers.ts
- gulpfile.js
- package.json
- upgrade gulp-typescript / typescript
- clear typescript compile errors
- TS 1.8 -> https://github.com/Microsoft/TypeScript/wiki/Roadmap
Closes #2583
> chore(deps): 2583 allow more es6 syntax

- app/scripts/annotations/module.ts
- app/scripts/files/module.ts
> fix(route): 2488 empty page when param is missing

- app/scripts/components/facets/facets.directives.ts
- app/scripts/components/facets/facets.services.ts
- app/scripts/components/facets/templates/facets-free-text.html
- app/scripts/components/facets/templates/facets-prefix.html
- app/scripts/components/facets/templates/facets-section.html
- app/scripts/files/templates/file.html
- app/scripts/search/search.participants.table.model.ts
- set prefix facet w/ everything else,
otherwise prefix facet will appear multiple times once custom
free-text facets can be added
- remove link to case entity pg from file pg, no case pg in legacy
Closes #1222
> feat(facets): 1222 allow custom facet ids

- app/scripts/app.ts
- app/scripts/components/facets/facets.controllers.ts
- app/scripts/components/quick-search/quick-search.directives.ts
- app/scripts/components/user/user.services.ts
- app/scripts/core/core.services.ts
- app/scripts/core/tests/core.tests.js
- bower.json
- karma.conf.js
- remove ctrl+space listener (didn't work)
Closes #2513
> fix(quicksearch): 2513 unhighlight, open on enter

- app/scripts/components/facets/facets.directives.ts
- app/scripts/components/facets/templates/facets-free-text.html
- app/scripts/components/facets/templates/facets-prefix.html
- https://github.com/angular-ui/bootstrap/issues/759#issuecomment-123722242
Closes #9
> feat(facet): LGCY-9 open typeahead on input click

- CHANGELOG.md
- app/scripts/components/facets/templates/current.html
- package.json
> fix(facets): LGCY-15 humanify current filter

- CHANGELOG.md
- app/scripts/components/header/header.controller.ts
- app/scripts/components/header/templates/header.html
- app/styles/header.less
- package.json
> fix(app): PRTL-237 data status banner

- app/styles/app.less
not sure how this got in for legacy only, removing it in any case
Closes LGCY-16
> fix(styles): LGCY-16 remove break all from notify

- app/scripts/components/facets/templates/current.html
this commit https://github.com/NCI-GDC/portal-ui-legacy/commit/734aa0cdebc53a3f9d236a8ac197b3d15d8c796e forgot this spot
Closes LGCY-14
> fix(facets): LGCY-14 don't humanify in current

- app/scripts/files/files.directives.ts
> fix(manifest): [LGCY-31] dont allow DL when in progress

- app/scripts/app.ts
- app/scripts/components/user/user.services.ts
- bower.json
- & fix error in error handler
> feat(user): PRTL-278 dl refresh token (#1081)

- app/scripts/components/facets/templates/facet.html
- app/scripts/search/search.files.table.model.ts
- app/scripts/search/search.participants.table.model.ts
- fix tooltip not showing up on checked facet
> :sparkles: [LGCY-25] add tooltip to 'Platform' and 'Race' facets

- app/index.html
- app/scripts/app.ts
- app/scripts/components/facets/templates/facet.html
- app/scripts/components/facets/templates/facets-prefix.html
- app/scripts/components/header/templates/header.html
- app/styles/app.less
- app/styles/pagination.less
- append facet field name to term facet labels so no repeat labels with
just terms
- configure ngAria to not add tabindex 0 to everything, including the
root element, messing up skip link being first focus
- colour contrast
> :wheelchair: LGCY-79 508 fixes

- app/index.html
- app/scripts/components/header/header.directive.ts
- app/scripts/components/header/templates/banner.html
- app/styles/header.less
- bower.json
> :sparkles: LGCY-80 notifications: markdown support
